name: Update Fixtures

on:
  schedule:
    - cron: '23 * * * *' 
  workflow_dispatch:       # manual run button

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Save run time
        run: date -u +"%Y-%m-%dT%H:%M:%S"Z > last-run.txt

      - name: Commit timestamp
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add last-run.txt

          git commit -m "Add timestamp" || echo "No changes"

          git pull --rebase origin main
          git push origin main

      - name: Run API script
        env:
          FTBL_KEY: ${{ secrets.FTBL_KEY }}
        run: node scripts/api.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/fixtures.json

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Update fixtures"
            git push
          fi